# Site settings
title: "Project Myriad Documentation"
description: "The Definitive Manga and Anime Platform - Documentation and API Reference"
baseurl: ""
url: "https://heartless-veteran.github.io/Project-Myriad"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Navigation
header_pages:
  - README.md
  - docs/INDEX.md
  - ARCHITECTURE.md
  - DEVELOPMENT.md
  - CONTRIBUTING.md

# Exclude from processing
exclude:
  - .git
  - .github
  - gradle
  - gradlew
  - gradlew.bat
  - app
  - build.gradle.kts
  - settings.gradle.kts
  - local.properties.example
  - scripts
  - config