name: Bug Report
description: File a bug report for Project Myriad
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - HeartlessVeteran2
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: android-version
    attributes:
      label: Android Version
      description: What version of Android are you running?
      placeholder: ex. Android 14 (API 35)
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of Project Myriad are you using?
      placeholder: ex. 1.0.0
    validations:
      required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of the app is affected?
      options:
        - The Vault (Local Media)
        - AI Core (OCR/Translation)
        - The Browser (Online Discovery)
        - UI/UX
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Heartless-Veteran/Project-Myriad/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true