name: Auto-fix - Code Formatting

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  contents: write # Needed to commit changes to the PR branch
  pull-requests: read

jobs:
  autofix:
    name: Auto-format Code
    runs-on: ubuntu-latest
    # Only run on PRs from forks or if manually triggered
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          # We need to fetch the branch history to push changes back to it
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run ESLint autofix
        run: npx eslint --fix . || true
      
      - name: Run Prettier formatting
        run: npx prettier --write "**/*.{js,jsx,ts,tsx,json,md,yml,yaml}" --ignore-path .gitignore || true
      
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "style: Automated code formatting [skip ci]"
          git push
          
      - name: Summary
        run: |
          if [ "${{ steps.verify-changed-files.outputs.changed }}" == "true" ]; then
            echo "✅ Code formatting applied and committed"
          else
            echo "✅ No formatting changes needed"
          fi
