name: Development - Kotlin Setup

on:
  workflow_call:
    # This workflow can be called by other workflows
  workflow_dispatch:
    # Allow manual triggering

permissions:
  contents: read

jobs:
  setup-kotlin:
    name: Setup Kotlin Environment
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@v1
        with:
          version: '1.9.20'
          
      - name: Verify Kotlin installation
        run: |
          kotlin -version
          kotlinc -version
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        
      - name: Verify Gradle setup
        run: ./gradlew --version
