name: Dependency Security Check

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  pull_request:
    paths:
      - 'package.json'
      - 'android/build.gradle'
      - 'android/app/build.gradle'
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      
    - name: Setup Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version: '22'
        
    - name: Cache node modules
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Check for outdated packages
      run: npm outdated || true
      
    - name: Run security audit
      run: npm audit --audit-level=moderate || true
      
    - name: Run tests
      run: npm test
