name: Security - Dependency Check

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'android/build.gradle'
      - 'android/app/build.gradle'
      - 'build.gradle.kts'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  dependency-check:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Check for outdated packages
      run: npm outdated || true
      
    - name: Run security audit
      run: npm audit --audit-level=moderate --output=json > npm-audit.json || true
      
    - name: Upload npm audit results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: npm-audit-results
        path: npm-audit.json
        retention-days: 30
      
    - name: Run tests
      run: npm test
      
  gradle-security:
    name: Gradle Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      
    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew
      
    - name: Run Gradle dependency check
      run: ./gradlew dependencyCheckAnalyze --no-daemon || true
      
    - name: Generate dependency report
      run: ./gradlew dependencies --no-daemon > gradle-dependencies.txt || true
      
    - name: Upload Gradle security results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: gradle-security-results
        path: |
          gradle-dependencies.txt
          build/reports/
        retention-days: 30
