name: Quality - GitHub Checks

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [ main, alpha ]
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  actions: read

jobs:
  github-checks:
    name: Run GitHub Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Run linting
        id: lint
        run: npm run lint
        continue-on-error: true
        
      - name: Run tests
        id: test
        run: npm test
        continue-on-error: true
        
      - name: Create GitHub Check - Linting
        uses: LouisBrunner/checks-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: 'Code Linting'
          conclusion: ${{ steps.lint.outcome }}
          output: |
            **Linting Results**
            
            ESLint check completed with status: ${{ steps.lint.outcome }}
            
      - name: Create GitHub Check - Testing
        uses: LouisBrunner/checks-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: 'Unit Tests'
          conclusion: ${{ steps.test.outcome }}
          output: |
            **Test Results**
            
            Test suite completed with status: ${{ steps.test.outcome }}
