---
name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate Dokka documentation
        run: ./gradlew app:dokkaGenerateModuleHtml --stacktrace
        continue-on-error: true

      - name: Set up Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '18'

      - name: Update README statistics
        run: |
          if [ -f scripts/update-readme-stats.js ]; then
            node scripts/update-readme-stats.js
          fi
        continue-on-error: true

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Setup Ruby for Jekyll
        uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 # v1.197.0
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Jekyll dependencies
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Prepare site content
        run: |
          # Copy generated API documentation if it exists
          if [ -d app/build/dokka-module/html/module ]; then
            mkdir -p api
            cp -r app/build/dokka-module/html/module/* api/
            echo "✅ Dokka API documentation copied to api/"
          else
            echo "⚠️ No Dokka documentation found, creating placeholder"
            mkdir -p api
            echo "# API Documentation\n\nAPI documentation will be available after the first successful build." > api/index.md
          fi
          
          # Validate critical files exist
          echo "🔍 Validating site structure..."
          for file in index.html _config.yml docs/index.html; do
            if [ -f "$file" ]; then
              echo "✅ Found: $file"
            else
              echo "❌ Missing: $file"
              exit 1
            fi
          done

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --verbose --trace
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: '_site'

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5