---
name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate Dokka documentation
        run: ./gradlew app:dokkaGenerateModuleHtml

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'

      - name: Update README statistics
        run: |
          if [ -f scripts/update-readme-stats.js ]; then
            node scripts/update-readme-stats.js
          fi
        continue-on-error: true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Prepare site content
        run: |
          mkdir -p _site
          
          # Copy markdown documentation
          cp -r docs/* _site/
          
          # Copy generated API documentation if it exists
          if [ -d app/build/dokka-module/html/module ]; then
            mkdir -p _site/api
            cp -r app/build/dokka-module/html/module/* _site/api/
          fi
          
          # Copy root documentation files
          cp README.md _site/
          cp ARCHITECTURE.md _site/ 2>/dev/null || true
          cp DEVELOPMENT.md _site/ 2>/dev/null || true
          cp CONTRIBUTING.md _site/ 2>/dev/null || true
          cp ROADMAP.md _site/ 2>/dev/null || true
          cp SECURITY.md _site/ 2>/dev/null || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4