name: Code Quality - Super Linter

on:
  push:
    branches: [ main, alpha ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  # To report GitHub Actions status checks
  statuses: write

jobs:
  super-linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
          
      - name: Lint Code Base
        uses: super-linter/super-linter@v8
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The following are linter rules we want to enable
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_KOTLIN: true
          VALIDATE_JAVA: true
          # Disable some linters that might be too strict
          VALIDATE_JSCPD: false
          VALIDATE_CSS: false
          DEFAULT_BRANCH: main
